name: ICPF
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - accelerate==0.28.0
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - altair==5.2.0
      - angle-emb==0.3.10
      - annotated-types==0.6.0
      - anyio==4.3.0
      - attrs==23.2.0
      - axial-positional-embedding==0.2.1
      - bitsandbytes==0.43.0
      - boltons==24.0.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clip==0.2.0
      - colorama==0.4.6
      - colt5-attention==0.11.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - datasets==2.18.0
      - deepspeed==0.14.0
      - dill==0.3.8
      - einops==0.8.0
      - einops-exts==0.0.4
      - et-xmlfile==1.1.0
      - fastapi==0.110.0
      - ffmpy==0.3.2
      - filelock==3.13.1
      - fonttools==4.49.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.21.0
      - gradio-client==0.12.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - idna==3.6
      - importlib-resources==6.3.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - littleutils==0.2.4
      - local-attention==1.9.14
      - markdown-it-py==3.0.0
      - markdown2==2.4.13
      - markupsafe==2.1.3
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numpy==1.26.4
      - ogb==1.3.6
      - openpyxl==3.1.2
      - orjson==3.9.15
      - outdated==0.2.2
      - packaging==24.0
      - pandas==2.2.1
      - peft==0.9.0
      - pillow==10.2.0
      - prettytable==3.10.0
      - product-key-memory==0.2.11
      - protobuf==4.25.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.1
      - pyarrow-hotfix==0.6
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydub==0.25.1
      - pygments==2.17.2
      - pynvml==11.5.0
      - pypandoc==1.13
      - pyparsing==3.1.2
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.33.0
      - regex==2023.12.25
      - requests==2.31.0
      - rich==13.7.1
      - rpds-py==0.18.0
      - ruff==0.3.2
      - safetensors==0.4.2
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.5.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - sinkhorn-transformer==0.11.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - starlette==0.36.3
      - sympy==1.12
      - termcolor==2.4.0
      - threadpoolctl==3.3.0
      - tiktoken==0.6.0
      - timm==0.9.16
      - tokenizers==0.15.2
      - tomlkit==0.12.0
      - toolz==0.12.1
      - tqdm==4.66.2
      - transformers==4.38.2